config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
    path('category/<slug:category_slug>/', views.CategoryView.as_view(), name='category_filter'),
]

orders/models.py
from django.db import models

# Create your models here.

orders/forms.py
from django import forms


class CartAddForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, max_value=9)

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .cart import Cart
from shop.models import Product
from .forms import CartAddForm


class CartView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'orders/cart.html', {'cart':cart})

    def post(self, request):
        pass


class CartAddView(View):
    def post(self, request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        form = CartAddForm(request.POST)
        if form.is_valid():
            cart.add(product, form.cleaned_data['quantity'])
        return redirect('orders:cart')


class CartRemoveView(View):
	def get(self, request, product_id):
		cart = Cart(request)
		product = get_object_or_404(Product, id=product_id)
		cart.remove(product)
		return redirect('orders:cart')

orders/templates/orders/cart.html
{% extends 'base.html' %}

{% block content %}
<section class="padding-y bg-light">
    <div class="container">
    <!-- =================== COMPONENT CART+SUMMARY ====================== -->
    <div class="row">
        <div class="col-lg-9">
    
            <div class="card">
            <div class="content-body">
                <h4 class="card-title mb-4">Your shopping cart</h4>
                




                <table class="table table-bordered">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Unit Price</th>
                        <th scope="col">Total Price</th>
                        <th scope="col">Operation</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for item in cart %}
                      <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ item.product }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>{{ item.price }}</td>
                        <td>{{ item.total_price }}</td>
                        <td><a href="{% url 'orders:cart_remove' item.product.id %}" class="btn btn-sm btn-danger">Delete</a></td>
                      </tr>
                    {% endfor %}
                    <tr>
                        <td>Total</td>
                        <td colspan="4"></td>
                        <td>{{ cart.get_total_price }}</td>
                    </tr>
                    </tbody>
                </table>



    
            </div> <!-- card-body .// -->
    
            <div class="content-body border-top">
                <p><i class="me-2 text-muted fa-lg fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
            </div> <!-- card-body.// -->
    
            </div> <!-- card.// -->
    
        </div> <!-- col.// -->
        <aside class="col-lg-3">
    
            <div class="card mb-3">
            <div class="card-body">
            <form>
                <div class="form-group">
                    <label class="form-label">Have coupon?</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="" placeholder="Coupon code">
                        <button class="btn btn-light">Apply</button>
                    </div>
                </div>
            </form>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
            <div class="card">
            <div class="card-body">
                <dl class="dlist-align">
                  <dt>Total price:</dt>
                  <dd class="text-end"> $329.00</dd>
                </dl>
                <dl class="dlist-align">
                  <dt>Discount:</dt>
                  <dd class="text-end text-success"> - $60.00 </dd>
                </dl>
                <dl class="dlist-align">
                  <dt>TAX:</dt>
                  <dd class="text-end"> $14.00 </dd>
                </dl>
                <hr>
                <dl class="dlist-align">
                  <dt>Total:</dt>
                  <dd class="text-end text-dark h5"> $357.90 </dd>
                </dl>
                
                <div class="d-grid gap-2 my-3">
                    <a href="#" class="btn btn-success w-100"> Make Purchase </a>
                    <a href="#" class="btn btn-light w-100"> Back to shop </a>
                </div>
            </div> <!-- card-body.// -->
            </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
    
    </div> <!-- row.// -->
    <!-- =================== COMPONENT 1 CART+SUMMARY .//END  ====================== -->
    
    <br><br>
    
    </div> <!-- container .//  -->
</section>

<section class="padding-y border-top">
<div class="container">
	<header class="section-heading">
		<h4 class="section-title">Recommended items</h4>
	</header> 

	<div class="row">
		<div class="col-lg-3 col-sm-6 col-12">
			<figure class="card card-product-grid">
				<div class="img-wrap">
					<span class="topbar">
						<a href="#" class="float-end"><i class="fa fa-lg fa-heart"></i></a>
						<span class="badge bg-danger"> New </span>
					</span>
					<a href="#"><img src="images/items/7.jpg"></a>
				</div>
				<figcaption class="info-wrap border-top">
					<a href="#" class="title">Gaming Headset with Mic</a>
						<div class="price-wrap mb-3">
							<strong class="price">$18.95</strong>
							<del class="price-old">$24.99</del>
						</div> <!-- price-wrap.// -->
						<a href="#" class="btn btn-outline-primary w-100">Add to cart</a>
				</figcaption>
			</figure> <!-- card // -->
		</div> <!-- col.// -->
		<div class="col-lg-3 col-sm-6 col-12">
			<figure class="card card-product-grid">
				<div class="img-wrap"> 
					<span class="topbar">
						<a href="#" class="float-end"><i class="fa fa-lg fa-heart"></i></a>
					</span>
					<a href="#"><img src="images/items/8.jpg"></a>
				</div>
				<figcaption class="info-wrap border-top">
					<a href="#" class="title">Apple Watch Series 1 Sport </a>
					<div class="price-wrap mb-3">
						<strong class="price">$120.00</strong>
					</div> <!-- price-wrap.// -->
					<a href="#" class="btn btn-outline-primary w-100">Add to cart</a>
				</figcaption>
			</figure> <!-- card // -->
		</div> <!-- col.// -->
		<div class="col-lg-3 col-sm-6 col-12">
			<figure class="card card-product-grid">
				<div class="img-wrap"> 
					<span class="topbar">
						<a href="#" class="float-end"><i class="fa fa-lg fa-heart"></i></a>
					</span>
					<a href="#"><img src="images/items/9.jpg"></a>
				</div>
				<figcaption class="info-wrap border-top">
					<a href="#" class="title"> Men's Denim Jeans Shorts  </a>
					<div class="price-wrap mb-3">
						<strong class="price">$80.50</strong>
					</div> <!-- price-wrap.// -->
					<a href="#" class="btn btn-outline-primary w-100">Add to cart</a>
				</figcaption>
			</figure> <!-- card // -->
		</div> <!-- col.// -->
		<div class="col-lg-3 col-sm-6 col-12">
			<figure class="card card-product-grid">
				<div class="img-wrap"> 
					<span class="topbar">
						<a href="#" class="float-end"><i class="fa fa-lg fa-heart"></i></a>
					</span>
					<a href="#"><img src="images/items/10.jpg"></a>
				</div>
				<figcaption class="info-wrap border-top">
					<a href="#" class="title text-truncate">Mens T-shirt Cotton Base Layer Slim fit </a>
					<div class="price-wrap mb-3">
						<strong class="price">$13.90</strong>
					</div> <!-- price-wrap.// -->
					<a href="#" class="btn btn-outline-primary w-100">Add to cart</a>
				</figcaption>
			</figure> <!-- card // -->
		</div> <!-- col.// -->
	</div> <!-- row.// -->
	
</div> <!-- container .//  -->
</section>

{% endblock content %}