config/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'
urlpatterns = [
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
]

shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('<slug:slug>/', views.DetailView.as_view(), name='detail'),
    path('category/<slug:category_slug>/', views.CategoryView.as_view(), name='category_filter'),
]

shop/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse



class Category(models.Model):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, related_name='scategory', null=True, blank=True)
    is_sub = models.BooleanField(default=False)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_filter', args=[self.slug,])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d/')
    description = models.TextField()
    price = models.IntegerField()
    available = models.BooleanField(default=True)
    publish = models.DateTimeField(default=timezone.now, verbose_name='Publish')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'
        ordering = ('name',)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:detail', args=[self.slug,])

shop/views.py
from django.shortcuts import render
from django.views import View
from .models import Product, Category
from orders.forms import CartAddForm


class HomeView(View):
    def get(self, request, category_slug=None):
        products = Product.objects.all()
        categories = Category.objects.filter(is_sub=False)
        return render(request, 'shop/home.html', {'products':products, 'categories':categories})


class DetailView(View):
    def get(self, request, slug):
        form = CartAddForm()
        product = Product.objects.get(slug=slug)
        return render(request, 'shop/detail.html', {'product': product, 'form': form})


class CategoryView(View):
    def get(self, request, category_slug):

        category = Category.objects.get(slug=category_slug)
        products = Product.objects.filter(category=category)
        return render(request, 'shop/category.html', {'products': products})

shop/templates/shop/category.html
{% extends 'base.html' %}


{% block content %}

<section class="padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-lg-3">
    
    <button class="btn btn-outline-secondary mb-3 w-100  d-lg-none" data-bs-toggle="collapse" data-bs-target="#aside_filter">Show filter</button>
    
    <!-- ===== Card for sidebar filter ===== -->
    <div id="aside_filter" class="collapse card d-lg-block mb-5">
    
      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside1">
            <i class="icon-control fa fa-chevron-down"></i>   Related items 
          </a>
        </header>
        <div class="collapse show" id="collapse_aside1">
          <div class="card-body">
            <ul class="list-menu">
              <li><a href="#">Electronics </a></li>
              <li><a href="#">Accessories  </a></li>
              <li><a href="#">Home items </a></li>
              <li><a href="#">Men's clothing </a></li>
              <li><a href="#">Interior items </a></li>
              <li><a href="#">Magazines </a></li>
              <li><a href="#">Category name </a></li>
              <li><a href="#">Home items </a></li>
            </ul>
          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article> <!-- filter-group // -->
    
      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside_brands">
            <i class="icon-control fa fa-chevron-down"></i>  Brands 
          </a>
        </header>
        <div class="collapse show" id="collapse_aside_brands">
          <div class="card-body">
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Mercedes </span>
                <b class="badge rounded-pill bg-gray-dark float-end">120</b>
              </label> <!-- form-check end.// -->
    
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Toyota </span>
                <b class="badge rounded-pill bg-gray-dark float-end">15</b>
              </label> <!-- form-check end.// -->
    
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Mitsubishi </span>
                <b class="badge rounded-pill bg-gray-dark float-end">35</b>
              </label> <!-- form-check end.// -->
    
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label"> Nissan </span>
                <b class="badge rounded-pill bg-gray-dark float-end">89</b>
              </label> <!-- form-check end.// -->
    
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="">
                <span class="form-check-label"> Honda </span>
                <b class="badge rounded-pill bg-gray-dark float-end">30</b>
              </label> <!-- form-check end.// -->
    
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="">
                <span class="form-check-label"> Honda accord </span>
                <b class="badge rounded-pill bg-gray-dark float-end">30</b>
              </label> <!-- form-check end.// -->
          </div> <!-- card-body .// -->
        </div> <!-- collapse.// -->
      </article>
    
      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside2" aria-expanded="true">
            <i class="icon-control fa fa-chevron-down"></i>  Price 
          </a>
        </header>
        <div class="collapse show" id="collapse_aside2" style="">
          <div class="card-body">
            <input type="range" class="form-range" min="0" max="100">
            <div class="row mb-3">
              <div class="col-6">
                <label for="min" class="form-label">Min</label>
                <input class="form-control" id="min" placeholder="$0" type="number">
              </div> <!-- col end.// -->
    
              <div class="col-6">
                <label for="max" class="form-label">Max</label>
                <input class="form-control" id="max" placeholder="$1,0000" type="number">
              </div> <!-- col end.// -->
            </div> <!-- row end.// -->
            <button class="btn btn-light w-100" type="button">Apply</button>
          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article> <!-- filter-group // -->
    
      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside3" aria-expanded="true">
            <i class="icon-control fa fa-chevron-down"></i>  Size 
          </a>
        </header>
        <div class="collapse show" id="collapse_aside3" style="">
          <div class="card-body">
              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> XS </span>
              </label>
    
              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> SM </span>
              </label>
    
              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> LG </span>
              </label>
    
              <label class="checkbox-btn">
                <input type="checkbox">
                <span class="btn btn-light"> XXL </span>
              </label>
          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article>  <!-- filter-group // -->
    
      <article class="filter-group">
        <header class="card-header">
          <a href="#" class="title" data-bs-toggle="collapse" data-bs-target="#collapse_aside4" aria-expanded="true">
            <i class="icon-control fa fa-chevron-down"></i> Ratings
          </a>
        </header>
        <div class="collapse show" id="collapse_aside4" style="">
          <div class="card-body">
            
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 100%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 80%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 60%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->
              <label class="form-check mb-2">
                <input class="form-check-input" type="checkbox" value="" checked="">
                <span class="form-check-label">
                  <ul class="rating-stars">
                    <li class="stars-active" style="width: 40%;">
                      <img src="images/misc/stars-active.svg" alt="">
                    </li>
                    <li> <img src="images/misc/starts-disable.svg" alt="">  </li>
                  </ul>
                </span>
              </label> <!-- form-check end.// -->
            
    
          </div> <!-- card-body.// -->
        </div> <!-- collapse.// -->
      </article>  <!-- filter-group // -->
    
    </div> <!-- card.// -->
    <!-- ===== Card for sidebar filter .// ===== -->
    
        </aside> <!-- col .// -->
        <main class="col-lg-9">
            
        <header class="d-sm-flex align-items-center border-bottom mb-4 pb-3">
            <strong class="d-block py-2">32 Items found </strong>
            <div class="ms-auto">
              <select class="form-select d-inline-block w-auto">
                  <option value="0">Best match</option>
                  <option value="1">Recommended</option>
                  <option value="2">High rated</option>
                  <option value="3">Randomly</option>
              </select>
              <div class="btn-group">
                <a href="#" class="btn btn-light" data-bs-toggle="tooltip" title="" data-bs-original-title="List view"> 
                  <i class="fa fa-bars"></i>
                </a>
                <a href="#" class="btn btn-light active" data-bs-toggle="tooltip" title="" data-bs-original-title="Grid view"> 
                  <i class="fa fa-th"></i>
                </a>
              </div> <!-- btn-group end.// -->
            </div>
        </header>
    
        <!-- ========= content items ========= -->
        <div class="row">
            {% for product in products %}
            <div class="col-lg-4 col-md-6 col-sm-6">
              <figure class="card card-product-grid">
                <div class="img-wrap"> 
                  <img src="{{ product.image.url }}"> 
                </div>
                <figcaption class="info-wrap border-top">
                  <div class="price-wrap">
                    <strong class="price">$99.00</strong>
                    <del class="price-old">$170.00</del>
                  </div> <!-- price-wrap.// -->
                  <p class="title mb-2">T-shirts with multiple colors, for men and lady</p>
                  
                  <a href="#" class="btn btn-primary">Add to cart</a>
                  <a href="#" class="btn btn-light btn-icon"> <i class="fa fa-heart"></i> </a>
                </figcaption>
              </figure>
            </div> <!-- col end.// -->
            {% endfor %}
        </div> <!-- row end.// -->
    
        <hr>
    
        <footer class="d-flex mt-4">
          <div>
            <a href="javascript: history.back()" class="btn btn-light"> « Go back</a>
          </div>
          <nav class="ms-3">
            <ul class="pagination">
              <li class="page-item"><a class="page-link" href="#">1</a></li>
              <li class="page-item active" aria-current="page">
                <span class="page-link">2</span>
              </li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item">
                <a class="page-link" href="#">Next</a>
              </li>
            </ul>
          </nav>
        </footer>
    
        <!-- ========= content items .// ========= -->
    
        
    
        </main> <!-- col .// -->
    </div> <!-- row .// -->
    
    </div> <!-- container .//  -->
    </section>





{% endblock %}

shop/templates/shop/detail.html
{% extends 'base.html' %}


{% block content %}

<section class="padding-y">
    <div class="container">
    
    <div class="row">
    <aside class="col-lg-6">
      <article class="gallery-wrap"> 
        <div class="img-big-wrap img-thumbnail">
           <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big.jpg"> 
              <img height="560" src="{{ product.image.url }}"> 
           </a>
        </div> <!-- img-big-wrap.// -->
        <div class="thumbs-wrap">
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big1.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb1.jpg"> 
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big2.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb2.jpg">  
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big3.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb3.jpg">  
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big4.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb4.jpg">  
          </a>
          <a data-fslightbox="mygalley" data-type="image" href="images/items/detail1/big.jpg" class="item-thumb"> 
            <img width="60" height="60" src="images/items/detail1/thumb.jpg">  
          </a>
        </div> <!-- thumbs-wrap.// -->
      </article> <!-- gallery-wrap .end// -->
    </aside>
    <main class="col-lg-6">
      <article class="ps-lg-3">
        <h4 class="title text-dark">{{ product.name }}</h4>
        <div class="rating-wrap my-3">
          <ul class="rating-stars">
            <li style="width:80%" class="stars-active"> <img src="images/misc/stars-active.svg" alt=""> </li>
            <li> <img src="images/misc/starts-disable.svg" alt=""> </li>
          </ul>
          <b class="label-rating text-warning"> 4.5</b>
          <i class="dot"></i>
          <span class="label-rating text-muted"> <i class="fa fa-shopping-basket"></i> 154 orders </span>
          <i class="dot"></i>
          <span class="label-rating text-success">In stock</span>
        </div> <!-- rating-wrap.// -->
    
        <div class="mb-3"> 
          <var class="price h5">${{ product.price }}</var> 
          <span class="text-muted">/per box</span> 
        </div> 
    
        <p>{{ product.description }}</p>
    
        <dl class="row">
          <dt class="col-3">Type:</dt>
          <dd class="col-9">Regular</dd>
    
          <dt class="col-3">Color</dt>
          <dd class="col-9">Brown</dd>
    
          <dt class="col-3">Material</dt>
          <dd class="col-9">Cotton, Jeans </dd>
    
          <dt class="col-3">Brand</dt>
          <dd class="col-9">Reebook </dd>
        </dl>
    
        <hr>
    
        <div class="row mb-4">
          <div class="col-md-4 col-6 mb-2">
            <label class="form-label">Size</label>
            <select class="form-select">
              <option>Small</option>
              <option>Medium</option>
              <option>Large</option>
            </select>
          </div> <!-- col.// -->
          
        </div> <!-- row.// -->

        <div class="row">
          <div class="col-12 mb-3">
            <form action="{% url 'orders:cart_add' product.id %}" method="POST">
              {% csrf_token %}
              {{ form }}
              <input class="btn btn-sm btn-primary" type="submit" Value="Add to cart">
            </form>
          </div> <!-- col.// -->
        </div>
    

        <a href="#" class="btn  btn-light"> <i class="me-1 fa fa-heart"></i> Save </a>
      
      </article> <!-- product-info-aside .// -->
    </main> <!-- col.// -->
    </div> <!-- row.// -->
    
    </div> <!-- container .//  -->
    </section>

{% endblock %}

shop/templates/shop/home.html
{% extends 'base.html' %}


{% block content %}
<!-- ================ SECTION INTRO ================ -->
<section class="section-intro padding-top-sm">
	<div class="container">
	<main class="card p-3">
		<div class="row">
			<aside class="col-lg-3"> 
				<nav class="nav flex-column nav-pills">
					{% for cat in categories %}
						<a class="nav-link" href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
					{% endfor %}


				</nav>
			</aside>
			<div class="col-lg-9">
				<article class="card-banner p-5 bg-primary" style="height: 360px">
					<div style="max-width: 500px">
			        <h2 class="text-white">Great products with <br> best deals </h2>
			        <p class="text-white">No matter how far along you are in your sophistication as an amateur astronomer, there is always one.</p>
			        <a href="#" class="btn btn-warning"> View more </a>
			        </div>
				</article>
			</div>
		</div>
	</main>
	</div> <!-- container end.// -->
</section>
<!-- ================ SECTION INTRO END.// ================ -->


<!-- ================ SECTION PRODUCTS ================ -->
<section class="padding-top">
<div class="container">

	<header class="section-heading">
		<h3 class="section-title">New products</h3>
	</header> 

	<div class="row">
		{% for product in products %}
		
		<div class="col-lg-3 col-md-6 col-sm-6">
			<figure class="card card-product-grid">
				<a href="{{ product.get_absolute_url }}" class="img-wrap"> 
					<span class="topbar"> <b class="badge bg-success"> Offer </b> </span>
					<img src="{{ product.image.url }}"> 
				</a>
				<figcaption class="info-wrap border-top">
					<a href="#" class="float-end btn btn-light btn-icon"> <i class="fa fa-heart"></i> </a>
					<a href="#" class="title text-truncate">{{ product.name }}</a>
					<small class="text-muted">Sizes: S, M, XL</small>
					<div class="price-wrap">
						<span class="price">${{ product.price }}</span> <del class="price-old">$20</del>
					</div> <!-- price-wrap.// -->
				</figcaption>
			</figure>
		</div> <!-- col end.// -->
		{% endfor %}

	</div> <!-- row end.// -->

</div> <!-- container end.// -->
</section>
<!-- ================ SECTION PRODUCTS END.// ================ -->


<!-- ================ SECTION FEATURE ================ -->
<section class="padding-top">
<div class="container">
	<div class="row gy-4">
		<aside class="col-lg-6">
		  <article class="card-banner bg-gray h-100" style="min-height: 200px">
		    <div class="p-3 p-lg-5"  style="max-width:70%">
		      <h3> Best products & brands in our store at 80% off</h3>
		      <p>That's true but not always</p>
		      <a class="btn btn-warning" href="#"> Claim offer </a>
		    </div>
		    <img src="https://via.placeholder.com/400x400" height="350" class="img-bg">
		  </article>
		</aside> <!-- col.// -->
		<aside class="col-lg-6">

		  <div class="row mb-4">
		    <div class="col-6">
		      <article class="card bg-primary" style="min-height: 200px">
		        <div class="card-body">
		          <h5 class="text-white">Gaming toolset</h5>
		          <p class="text-white-50">Technology for cyber sport  </p>
		          <a class="btn btn-outline-light btn-sm" href="#">Learn more</a>
		        </div>
		      </article>
		    </div>
		    <div class="col-6">
		      <article class="card bg-primary" style="min-height: 200px">
		        <div class="card-body">
		          <h5 class="text-white">Quality sound</h5>
		          <p class="text-white-50">All you need for music</p>
		          <a class="btn btn-outline-light btn-sm" href="#">Learn more</a> 
		        </div>
		      </article>
		    </div>
		  </div> <!-- row.// -->

		  <article class="card bg-success" style="min-height: 200px">
		    <div class="card-body">
		      <h5 class="text-white">Buy 2 items, With special gift</h5>
		      <p class="text-white-50" style="max-width:400px;">Buy one, get one free marketing strategy helps your business improves the brand by sharing the profits </p>
		      <a class="btn btn-outline-light btn-sm" href="#">Learn more</a> 
		    </div>
		  </article>

		</aside> <!-- col.// -->
	</div> <!-- row.// -->
</div> <!-- container end.// -->
</section>
<!-- ================ SECTION FEATURE END.// ================ -->

<!-- ================ SECTION PRODUCTS ================ -->
<section class="padding-top">
<div class="container">

	<header class="section-heading">
		<h3 class="section-title">Recently viewed</h3>
	</header> 

	<div class="row gy-3">
		<div class="col-lg-2 col-md-4 col-4">
			<a href="#" class="img-wrap"> 
				<img height="200" width="200" class="img-thumbnail" src="https://via.placeholder.com/400x400"> 
			</a>
		</div> <!-- col.// -->
		<div class="col-lg-2 col-md-4 col-4">
			<a href="#" class="img-wrap"> 
				<img height="200" width="200" class="img-thumbnail" src="https://via.placeholder.com/400x400"> 
			</a>
		</div> <!-- col.// -->
		<div class="col-lg-2 col-md-4 col-4">
			<a href="#" class="img-wrap"> 
				<img height="200" width="200" class="img-thumbnail" src="https://via.placeholder.com/400x400"> 
			</a>
		</div> <!-- col.// -->
		<div class="col-lg-2 col-md-4 col-4">
			<a href="#" class="img-wrap"> 
				<img height="200" width="200" class="img-thumbnail" src="https://via.placeholder.com/400x400"> 
			</a>
		</div> <!-- col.// -->
		<div class="col-lg-2 col-md-4 col-4">
			<a href="#" class="img-wrap"> 
				<img height="200" width="200" class="img-thumbnail" src="https://via.placeholder.com/400x400"> 
			</a>
		</div> <!-- col.// -->
		<div class="col-lg-2 col-md-4 col-4">
			<a href="#" class="img-wrap"> 
				<img height="200" width="200" class="img-thumbnail" src="https://via.placeholder.com/400x400"> 
			</a>
		</div> <!-- col.// -->
	</div> <!-- row end.// -->

</div> <!-- container end.// -->
</section>
<!-- ================ SECTION PRODUCTS END.// ================ -->

<section class="padding-y">
  <div class="container">
	<article class="card p-3 p-lg-5">
		<div class="row g-3">
			<div class="col-lg-3 col-md-6">	
			<figure class="icontext">
				<div class="icon">
					<span class="icon-sm bg-warning-light text-warning rounded">
						<i class="fa fa-thumbs-up"></i>
					</span>
				</div>
				<figcaption class="text">
					<h6 class="title">Reasonable prices</h6>
					<p>Have you ever finally just  </p>
				</figcaption>
			</figure> <!-- icontext // -->
			</div><!-- col // -->
			<div class="col-lg-3 col-md-6">	
			<figure class="icontext">
				<div class="icon">
					<span class="icon-sm bg-warning-light text-warning rounded">
						<i class="fa fa-plane"></i>
					</span>
				</div>
				<figcaption class="text">
					<h6 class="title">Worldwide shipping</h6>
					<p>Have you ever finally just  </p>
				</figcaption>
			</figure> <!-- icontext // -->
			</div><!-- col // -->
			<div class="col-lg-3 col-md-6">	
			<figure class="icontext">
				<div class="icon">
					<span class="icon-sm bg-warning-light text-warning rounded">
						<i class="fa fa-star"></i>
					</span>
				</div>
				<figcaption class="text">
					<h6 class="title">Best ratings</h6>
					<p>Have you ever finally just  </p>
				</figcaption>
			</figure> <!-- icontext // -->
			</div> <!-- col // -->
			<div class="col-lg-3 col-md-6">	
			<figure class="icontext">
				<div class="icon">
					<span class="icon-sm bg-warning-light text-warning rounded">
						<i class="fa fa-phone"></i>
					</span>
				</div>
				<figcaption class="text">
					<h6 class="title">Help center</h6>
					<p>Have you ever finally just  </p>
				</figcaption>
			</figure> <!-- icontext // -->
			</div> <!-- col // -->
		</div> <!-- row // -->
	</article>
  </div><!-- //container -->
</section>


{% endblock %}